### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by EmileTrotignon** [Shuumatsu/vscode-ocamlformat#1]
It's not working. Too bad I really like ocamlformat, and VScode is a lot better than emacs.
The error message I got is : 

> Command failed: cd /home/emile/etudes/L3_ENS/projet_programmation1/project/mcc && /home/emile/.opam/system/bin/ocamlformat --name=/home/emile/etudes/L3_ENS/projet_programmation1/project/mcc/compile.ml /dev/stdin <<<'open Cparse open Genlab open Printf module Var = struct type t = string * int let compare (s, _) (s', _) = compare s s' end module Env = Set.Make (Var) let add_header out = Printf.fprintf out ".file	\"file.c\"\n .text\n .globl	main\n .type	main, @function\n" let compile_declarations out (dec_list : var_declaration list) : unit = let rec compile_declaration (env, stack_head) decl = match decl with | CDECL (loc, name) -> (Env.add (name, stack_head) env), stack_head + 1 | CFUN (loc, name, args, code) -> fprintf out "%s:\n pushq	%%rbp\n movq	
> %%rsp, %%rbp\n" name ; let (env', stack_head') = compile_declarations' (Env.empty, 0) args in let r = compile_code (env', stack_head') code in fprintf out "popq	%%rbp\n" ; ...

**Comment by Shuumatsu** [comment]
I cannot reproduce this error on my archlinux machine, but I did make some changes to the code. 
In fact, I don't know why there was `cd /home/emile/etudes/L3_ENS/projet_programmation1/project/mcc &&` when using this ext.

Anyway, you can try the new version by search `ocamlformat` inside vscode ext market.
